<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="4" total="17" passed="13">
  <reporter-output>
  </reporter-output>
  <suite name="galePartnersTestAssignment.unitTestClass" duration-ms="286540" started-at="2015-09-09T03:40:42Z" finished-at="2015-09-09T03:45:28Z">
    <groups>
    </groups>
    <test name="galePartnersTestAssignment.unitTestClass" duration-ms="286540" started-at="2015-09-09T03:40:42Z" finished-at="2015-09-09T03:45:28Z">
      <class name="galePartnersTestAssignment.unitTestClass">
        <test-method status="PASS" signature="setUp()[pri:0, instance:galePartnersTestAssignment.unitTestClass@577fe2b3]" name="setUp" is-config="true" duration-ms="5430" started-at="2015-09-09T09:10:42Z" finished-at="2015-09-09T09:10:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="emailFieldTestForInValidInput()[pri:0, instance:galePartnersTestAssignment.unitTestClass@577fe2b3]" name="emailFieldTestForInValidInput" duration-ms="33072" started-at="2015-09-09T09:10:47Z" finished-at="2015-09-09T09:11:20Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at galePartnersTestAssignment.unitTestClass.emailFieldTestForInValidInput(unitTestClass.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- emailFieldTestForInValidInput -->
        <test-method status="PASS" signature="emailFieldTestForValidInput()[pri:0, instance:galePartnersTestAssignment.unitTestClass@577fe2b3]" name="emailFieldTestForValidInput" duration-ms="19167" started-at="2015-09-09T09:11:20Z" finished-at="2015-09-09T09:11:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- emailFieldTestForValidInput -->
        <test-method status="FAIL" signature="firstNameFieldTestForInValidInput()[pri:0, instance:galePartnersTestAssignment.unitTestClass@577fe2b3]" name="firstNameFieldTestForInValidInput" duration-ms="18044" started-at="2015-09-09T09:11:39Z" finished-at="2015-09-09T09:11:57Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at galePartnersTestAssignment.unitTestClass.firstNameFieldTestForInValidInput(unitTestClass.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- firstNameFieldTestForInValidInput -->
        <test-method status="FAIL" signature="firstNameFieldTestForOutOfBoundInput()[pri:0, instance:galePartnersTestAssignment.unitTestClass@577fe2b3]" name="firstNameFieldTestForOutOfBoundInput" duration-ms="17412" started-at="2015-09-09T09:11:57Z" finished-at="2015-09-09T09:12:15Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at galePartnersTestAssignment.unitTestClass.firstNameFieldTestForOutOfBoundInput(unitTestClass.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- firstNameFieldTestForOutOfBoundInput -->
        <test-method status="PASS" signature="firstNameFieldTestForValidInput()[pri:0, instance:galePartnersTestAssignment.unitTestClass@577fe2b3]" name="firstNameFieldTestForValidInput" duration-ms="18813" started-at="2015-09-09T09:12:15Z" finished-at="2015-09-09T09:12:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- firstNameFieldTestForValidInput -->
        <test-method status="PASS" signature="firstNameFieldTestWithSpacesInInput()[pri:0, instance:galePartnersTestAssignment.unitTestClass@577fe2b3]" name="firstNameFieldTestWithSpacesInInput" duration-ms="17364" started-at="2015-09-09T09:12:34Z" finished-at="2015-09-09T09:12:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- firstNameFieldTestWithSpacesInInput -->
        <test-method status="PASS" signature="lastNameFieldTestForInValidInput()[pri:0, instance:galePartnersTestAssignment.unitTestClass@577fe2b3]" name="lastNameFieldTestForInValidInput" duration-ms="7485" started-at="2015-09-09T09:12:51Z" finished-at="2015-09-09T09:12:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lastNameFieldTestForInValidInput -->
        <test-method status="PASS" signature="lastNameFieldTestForOutOfBoundInput()[pri:0, instance:galePartnersTestAssignment.unitTestClass@577fe2b3]" name="lastNameFieldTestForOutOfBoundInput" duration-ms="7471" started-at="2015-09-09T09:12:58Z" finished-at="2015-09-09T09:13:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lastNameFieldTestForOutOfBoundInput -->
        <test-method status="PASS" signature="lastNameFieldTestForValidInput()[pri:0, instance:galePartnersTestAssignment.unitTestClass@577fe2b3]" name="lastNameFieldTestForValidInput" duration-ms="17567" started-at="2015-09-09T09:13:06Z" finished-at="2015-09-09T09:13:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lastNameFieldTestForValidInput -->
        <test-method status="PASS" signature="lastNameFieldTestWithSpacesInInput()[pri:0, instance:galePartnersTestAssignment.unitTestClass@577fe2b3]" name="lastNameFieldTestWithSpacesInInput" duration-ms="17466" started-at="2015-09-09T09:13:23Z" finished-at="2015-09-09T09:13:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lastNameFieldTestWithSpacesInInput -->
        <test-method status="PASS" signature="testDisappearanceOfErrorMessageFirstNameInput()[pri:0, instance:galePartnersTestAssignment.unitTestClass@577fe2b3]" name="testDisappearanceOfErrorMessageFirstNameInput" duration-ms="17821" started-at="2015-09-09T09:13:41Z" finished-at="2015-09-09T09:13:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDisappearanceOfErrorMessageFirstNameInput -->
        <test-method status="PASS" signature="testDisappearanceOfErrorMessageLastNameInput()[pri:0, instance:galePartnersTestAssignment.unitTestClass@577fe2b3]" name="testDisappearanceOfErrorMessageLastNameInput" duration-ms="18212" started-at="2015-09-09T09:13:59Z" finished-at="2015-09-09T09:14:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDisappearanceOfErrorMessageLastNameInput -->
        <test-method status="PASS" signature="testEnterInValidPhoneNumber()[pri:0, instance:galePartnersTestAssignment.unitTestClass@577fe2b3]" name="testEnterInValidPhoneNumber" duration-ms="8156" started-at="2015-09-09T09:14:17Z" finished-at="2015-09-09T09:14:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testEnterInValidPhoneNumber -->
        <test-method status="PASS" signature="testEnterInValidPostCode()[pri:0, instance:galePartnersTestAssignment.unitTestClass@577fe2b3]" name="testEnterInValidPostCode" duration-ms="7662" started-at="2015-09-09T09:14:25Z" finished-at="2015-09-09T09:14:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testEnterInValidPostCode -->
        <test-method status="PASS" signature="testEnterValidPhoneNumber()[pri:0, instance:galePartnersTestAssignment.unitTestClass@577fe2b3]" name="testEnterValidPhoneNumber" duration-ms="18034" started-at="2015-09-09T09:14:33Z" finished-at="2015-09-09T09:14:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testEnterValidPhoneNumber -->
        <test-method status="PASS" signature="testEnterValidPostCode()[pri:0, instance:galePartnersTestAssignment.unitTestClass@577fe2b3]" name="testEnterValidPostCode" duration-ms="17519" started-at="2015-09-09T09:14:51Z" finished-at="2015-09-09T09:15:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testEnterValidPostCode -->
        <test-method status="FAIL" signature="testSelectPhoneType()[pri:0, instance:galePartnersTestAssignment.unitTestClass@577fe2b3]" name="testSelectPhoneType" duration-ms="19475" started-at="2015-09-09T09:15:08Z" finished-at="2015-09-09T09:15:28Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:165)
	at galePartnersTestAssignment.unitTestClass.testSelectPhoneType(unitTestClass.java:175)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSelectPhoneType -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:galePartnersTestAssignment.unitTestClass@577fe2b3]" name="tearDown" is-config="true" duration-ms="319" started-at="2015-09-09T09:15:28Z" finished-at="2015-09-09T09:15:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- galePartnersTestAssignment.unitTestClass -->
    </test> <!-- galePartnersTestAssignment.unitTestClass -->
  </suite> <!-- galePartnersTestAssignment.unitTestClass -->
</testng-results>
